dist: trusty
sudo: required
language: cpp
notifications:
    email: false
compiler:
    - clang
    - gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y clang-format-3.8
script: bash ./script/check_format.sh && mkdir build && cd build && cmake ../
